transformerlab/transformerlab-api

api.py

Check for inferenceParams key on experiment_config object.

Fix bug that breaks starting models on a new experiment

---

transformerlab/plugins/llama_trainer/index.json
transformerlab/plugins/llama_trainer/main.py

Made the default llama_trainer plugin actually work on ubuntu by moving the maximum sequence length and packing parameters to the config instead of the trainer. Also switched configs from TrainingArguments to SFTConfig as TrainingArguments doesnt support packing or maximum sequence length. 
Also removed the check for completion in the callback during training as it was prematurely stopping the training. Instead, the training finished when the trainer decides that the training is complete.

Make the default llama_trainer plugin work on ubuntu

---

transformerlab/routers/experiment/documents.py

Implement error handling to return a message when a specified folder does not exist during document list retrieval.

documents: send error if folder doesn't exist

---

transformerlab/plugins/mlx_vlm_server/main.py

Potential fix for [https://github.com/transformerlab/transformerlab-api/security/code-scanning/29](https://github.com/transformerlab/transformerlab-api/security/code-scanning/29)
To fix the SSRF vulnerability, we need to validate the `image_link` parameter to ensure it only allows URLs from trusted domains. This can be achieved by maintaining a list of authorized domains and checking if the `image_link` belongs to one of these domains before making the HTTP request.
1. Create a list of authorized domains.
2. Validate the `image_link` to ensure it belongs to one of the authorized domains.
3. If the `image_link` is not valid, handle the error appropriately.

Potential fix for code scanning alert no. 29: Full server-side request forgery

---

transformerlab/routers/experiment/export.py

Potential fix for [https://github.com/transformerlab/transformerlab-api/security/code-scanning/101](https://github.com/transformerlab/transformerlab-api/security/code-scanning/101)
To fix the problem, we should avoid returning the detailed exception message to the user. Instead, we can log the detailed error message on the server and return a generic error message to the user. This way, developers can still access the detailed error information for debugging purposes, but users will not see any sensitive information.
- Modify the code to log the detailed exception message using a logging library.
- Return a generic error message to the user instead of the detailed exception message.

Potential fix for code scanning alert no. 101: Information exposure through an exception

---

transformerlab/routers/jobs.py

Potential fix for [https://github.com/transformerlab/transformerlab-api/security/code-scanning/102](https://github.com/transformerlab/transformerlab-api/security/code-scanning/102)
To fix the problem, we need to ensure that detailed error messages, including stack traces, are not exposed to the user. Instead, we should log the detailed error message on the server and return a generic error message to the user. This can be achieved by modifying the exception handling code to log the exception and return a generic error message.
1. Import the `logging` module to enable logging of error messages.
2. Replace the current exception handling code to log the detailed error message and return a generic error message.

Potential fix for code scanning alert no. 102: Information exposure through an exception

---

transformerlab/routers/model.py

Potential fix for [https://github.com/transformerlab/transformerlab-api/security/code-scanning/104](https://github.com/transformerlab/transformerlab-api/security/code-scanning/104)
To fix the problem, we need to ensure that detailed exception messages are not exposed to the end user. Instead, we should log the detailed error message on the server and return a generic error message to the user. This can be achieved by modifying the exception handling code to log the exception and return a generic error message.
Specifically, we will:
1. Import the `logging` module to enable logging of exceptions.
2. Replace the return statement in the exception handling block with a logging statement and a generic error message.

Potential fix for code scanning alert no. 104: Information exposure through an exception

---

transformerlab/routers/model.py

Potential fix for [https://github.com/transformerlab/transformerlab-api/security/code-scanning/108](https://github.com/transformerlab/transformerlab-api/security/code-scanning/108)
To fix the problem, we need to ensure that detailed exception messages are not returned to the user. Instead, we should log the detailed error messages on the server and return a generic error message to the user. This can be achieved by modifying the exception handling blocks to log the error and return a generic message.
1. Modify the exception handling in the `download_huggingface_model` function to log the detailed error message and return a generic error message.
2. Modify the exception handling in the `download_model_by_huggingface_id` function to log the detailed error message and return a generic error …

Potential fix for code scanning alert no. 108: Information exposure through an exception

---

transformerlab/shared/shared.py

- Save model adaptors with secure_filename to find them correctly

Fixes bug caused by adding secure_filename in '/model/pefts' route

---

transformerlab/routers/model.py

Potential fix for [https://github.com/transformerlab/transformerlab-api/security/code-scanning/110](https://github.com/transformerlab/transformerlab-api/security/code-scanning/110)
To fix the problem, we need to ensure that detailed exception messages are not exposed to the end user. Instead, we should log the detailed error messages on the server and return a generic error message to the user. This can be achieved by modifying the `import_error` function to log the detailed error message and return a generic message.
1. Modify the `import_error` function in `transformerlab/routers/model.py` to log the detailed error message and return a generic error message.
2. Ensure that the logging configuration is set up to capture these logs.
_Suggested fixes powered by Copilot Autofix. Review …

Potential fix for code scanning alert no. 110: Information exposure through an exception

---

transformerlab/routers/train.py

Potential fix for [https://github.com/transformerlab/transformerlab-api/security/code-scanning/113](https://github.com/transformerlab/transformerlab-api/security/code-scanning/113)
To fix the problem, we should avoid sending the exception message directly to the user. Instead, we can log the detailed error message on the server and return a generic error message to the user. This approach ensures that sensitive information is not exposed while still allowing developers to debug issues using the server logs.
- Modify the exception handling block to log the exception message instead of returning it.
- Return a generic error message to the user.

Potential fix for code scanning alert no. 113: Information exposure through an exception

---

transformerlab/routers/model.py

Potential fix for [https://github.com/transformerlab/transformerlab-api/security/code-scanning/106](https://github.com/transformerlab/transformerlab-api/security/code-scanning/106)
To fix the problem, we need to ensure that detailed exception messages are not exposed to the user. Instead, we should log the detailed error message on the server and return a generic error message to the user. This can be achieved by modifying the exception handling in the `get_model_download_size` function.
1. Import the `logging` module if not already imported.
2. Log the detailed error message using `logging.error`.
3. Return a generic error message to the user.

Potential fix for code scanning alert no. 106: Information exposure through an exception

---

transformerlab/routers/data.py

Potential fix for [https://github.com/transformerlab/transformerlab-api/security/code-scanning/168](https://github.com/transformerlab/transformerlab-api/security/code-scanning/168)
To fix the problem, we need to ensure that detailed exception information is not exposed to the end user. Instead, we should log the detailed error message on the server and return a generic error message to the user. This can be achieved by using a logging mechanism to record the detailed error message and modifying the response to include a generic error message.
1. Import the `logging` module to enable logging of error messages.
2. Replace the return statement that includes the detailed error message with a logging statement and a return statement that includes a generic error message.
_Suggested fixes …

Potential fix for code scanning alert no. 168: Information exposure through an exception

---

transformerlab/routers/data.py

Potential fix for [https://github.com/transformerlab/transformerlab-api/security/code-scanning/169](https://github.com/transformerlab/transformerlab-api/security/code-scanning/169)
To fix the problem, we need to ensure that detailed error messages are not exposed to the end user. Instead, we should log the detailed error message on the server and return a generic error message to the user. This can be achieved by using Python's `logging` module to log the error and returning a generic error message in the response.
1. Import the `logging` module if it is not already imported.
2. Replace the current error handling code to log the detailed error message and return a generic error message.

Potential fix for code scanning alert no. 169: Information exposure through an exception

---

transformerlab/routers/tools.py

Potential fix for [https://github.com/transformerlab/transformerlab-api/security/code-scanning/172](https://github.com/transformerlab/transformerlab-api/security/code-scanning/172)
To fix the problem, we need to ensure that detailed error messages are not exposed to the end user. Instead, we should log the detailed error message on the server and return a generic error message to the user. This can be achieved by modifying the exception handling code to log the error and return a generic message.
- Modify the exception handling code in the `call_tool` function to log the detailed error message and return a generic error message.
- Add necessary imports for logging if not already present.

Potential fix for code scanning alert no. 172: Information exposure through an exception

---

transformerlab/routers/evals.py

Potential fix for [https://github.com/transformerlab/transformerlab-api/security/code-scanning/170](https://github.com/transformerlab/transformerlab-api/security/code-scanning/170)
To fix the problem, we should ensure that detailed exception messages are not exposed to the user. Instead, we should log the detailed error message on the server and return a generic error message to the user. This can be achieved by modifying the exception handling block to log the exception and return a generic error message.
1. Import the `logging` module to log the detailed error message.
2. Replace the `print(e)` statement with a logging statement.
3. Return a generic error message to the user instead of the detailed exception message.
_Suggested fixes powered by Copilot Autofix. Review carefully before …

Potential fix for code scanning alert no. 170: Information exposure through an exception

---

transformerlab/plugins/fastchat_server/model_worker.py

`torch.norm` has been deprecated for quite a while now. This fixes it 👍 
See: https://pytorch.org/docs/stable/generated/torch.norm.html

fix: remove use of deprecated `torch.norm`

---

transformerlab/routers/serverinfo.py

GPU was not accessed: GPU shows NaN on the dashboard. Refer to the below issue
https://github.com/transformerlab/transformerlab-app/issues/381
Server information was extracted in the `/info` endpoint, attached to the `get_computer_information` controller.
Server information was extracted using the `pynvml` library. 
At line 148, the device name is extracted, and it is represented as a byte string.
In the decoding process, an exception has been thrown 
`'utf-8' codec can't decode byte 0xf8 in position 0: invalid start byte`
Due to the exception handler, the line jumps to the catch block, appending the GPU information as 
```
g.append(
{
"name": "cpu",
"total_memory": "n/a",
"free_memory": "n/a",
"used_memory": "n/a",
"utilization": "n/a",
}
)
```
Ignore errors form using `device_name = …

Fixed: GPU did not access : GPU shows NaN

---

transformerlab/shared/download_huggingface_model.py

FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.

Fix `FutureWarning` about using resume_download with Huggingface

---

transformerlab/plugins/fastchat_server/index.json
transformerlab/plugins/fastchat_server/main.py
transformerlab/plugins/vllm_server/index.json
transformerlab/plugins/vllm_server/main.py

Address transformerlab/transformerlab-app#370
- Provides options to explicitly set dtypes of models from settings in FastChat server and vLLM server
- This would enable people with pre-Ampere GPUs (such as V100 and T4) to run models which support bfloat16 and float16 but get assigned bfloat16 (on auto dtypes) due to it being more preferred  (e.g. Deepseek R1 Qwen 1.5B)
- This will help the user from the above mentioned issue to use those models within the app easily

Changes to FastChat and vLLM to work with custom dtypes

---

transformerlab/routers/model.py

- Fixes transformerlab/transformerlab-app#227

Add model delete from hf cache logic

---

transformerlab/plugins/mlx_server/index.json
transformerlab/plugins/mlx_server/main.py
transformerlab/plugins/mlx_server/setup.sh

When we do this, we need to also upgrade our
MLX server to use the new location for generate_step which was moved in the mlx-lm lib from util.py to generate.py

Upgrade MLX-LM to 22.1

---

transformerlab/galleries/dataset-gallery.json

This stops messages (on-first start) like: 
```bash
❌ Unable to find local gallery file /Users/deep.gandhi/transformerlab-repos/transformerlab-api/transformerlab/galleries/dataset-gallery.json
```

Rename data gallery to prevent local local init errors

---

scripts/check_sizes_of_models.py
transformerlab/shared/download_huggingface_model.py

Fixes transformerlab/transformerlab-app#504
Fixes error printed because hub directory within cache doesn't exist when the first size check happens

Fix error of hub directory not existing for first model download

---

.github/workflows/release.yml
docker/common/Dockerfile
docker/gpu/nvidia/Dockerfile.cuda

The install dependencies part is moved to when we actually run the container so we don't need to actually have separate docker containers now

Fix Cuda docker and make it so that we only release one dockerfile from common

---

transformerlab/models/huggingfacemodel.py

Fixes failing downloads of some models like `IBM Granite v4 Tiny Preview` and `unsloth/gemma-3-4b-it-qat-int4-bnb-4bit`

Fix failing config.json download for some models

---

.github/workflows/release.yml
docker/gpu/amd/Dockerfile
docker/gpu/amd/README.md
docker/gpu/amd/entrypoint.sh

- We do not have a ROCM image for transformerlab-api
- This is the Dockerfile anyone can use to create the ROCM docker image for transformer lab
- The `entrypoint.sh` file was added because doing a direct execution with bash -c for entrypoint kept throwing errors even if the file system existed correctly
- Modified Github action to also release a `version-rocm` tagged image for rocm specifically

Add Docker for AMD GPUs

---

transformerlab/routers/data.py

Fixes: #689
https://github.com/transformerlab/transformerlab-app/issues/689
Fixed an issue where selecting a non-message-format column for the chat template preview would render nothing. Now, if the column isn't a list of { role, content } messages, the backend returns an error, and the frontend displays a clear warning instead of a blank preview.

Show Error When Chat Column Is Not in Valid Message Format

---

transformerlab/plugins/mlx_lora_trainer/index.json
transformerlab/plugins/mlx_lora_trainer/main.py
transformerlab/routers/jobs.py

We add a new endpoint that fetches checkpoints from a job. It is hardcoded to assume default paths that map to how MLX LoRA works (with checkpoints being stored alongside the adaptor).

Add an endpoint to fetch checkpoints from a job

---

requirements-no-gpu-uv.txt
requirements-rocm-uv.txt
requirements-rocm.in
requirements-uv.txt
requirements.in
transformerlab/plugins/fastchat_server/index.json
transformerlab/plugins/fastchat_server/setup.sh

- This PR upgrades transformers to v4.55.0
- We also add a bunch of setup code in fastchat server which installs torch v2.8 and a custom triton kernel following the instructions in [here](https://github.com/huggingface/gpt-oss-recipes).
- Depends on transformerlab/transformerlab-inference#18
- Once the tlab inference PR is approved, we need to do a release there and then upgrade the tlab inference versions here before merging

Upgrade transformers and add fastchat support for gpt-oss

---

api.py

Changed the returned process to a local variable. For starters, it is redundant because we pass a function that updates worker_process. But also it was setting worker_process on failure which, when combined with another bug we recently fixed, was causing all sorts of hard to debug errors.

Don't set worker process if model doesn't start
