transformerlab/shared/download_huggingface_model.py
Added case that HF_HOME has been set, so different huggingface home folder will be used
=> Change homefolder for huggingface models if HF_HOME is set

transformerlab/routers/data.py
and to include optional fields of 'limit' and 'offset'
=> Changing get request for data.py for pagination

transformerlab/plugins/autotrain_sft_trainer/index.json, transformerlab/plugins/autotrain_sft_trainer/main.py
Updated to autotrain plugin to actually work on Ubuntu
=> Make the autotrain plugin work on ubuntu

transformerlab/galleries/recipe-gallery.json
Changed the model being trained from gemma to TinyLlama, and changed the training plugin from sft_llama_factory to llama_trainer
=> fix the Dialogue summarizing recipe to actually work

transformerlab/galleries/recipe-gallery.json
Add a new recipe that acts as a sort of style transfer recipe, note it uses a dataset that is not in the training data gallery, but is instead just on huggingface.
=> add new recipe for pirate speech

transformerlab/plugins/llama_trainer/index.json, transformerlab/plugins/llama_trainer/main.py
The template model was already in the config, just switched to using it
=> switch llama_trainer from using the experiment model to the template model

transformerlab/routers/experiment/evals.py
=> Fix evals deletion

api.py, test/test_api_basic.py
This is a first test of our API endpoints -- just testing the home route for now to show how it is possible to test an API route
=> Create the first dummy Fast API test

transformerlab/plugin_sdk/transformerlab/plugin.py, transformerlab/plugins/autotrain_sft_trainer/main.py, transformerlab/plugins/basic_evals/index.json, transformerlab/plugins/basic_evals/main.py, transformerlab/plugins/basic_evals/setup.sh, transformerlab/plugins/common-eleuther-ai-lm-eval-harness-mlx/index.json, transformerlab/plugins/common-eleuther-ai-lm-eval-harness-mlx/main.py, transformerlab/plugins/common-eleuther-ai-lm-eval-harness-mlx/setup.sh, transformerlab/plugins/common-eleuther-ai-lm-eval-harness/index.json, transformerlab/plugins/common-eleuther-ai-lm-eval-harness/main.py, transformerlab/plugins/common-eleuther-ai-lm-eval-harness/setup.sh, transformerlab/plugins/deepeval_llm_judge/index.json, transformerlab/plugins/deepeval_llm_judge/main.py, transformerlab/plugins/deepeval_llm_judge/setup.sh, transformerlab/plugins/deepeval_objective/index.json, transformerlab/plugins/deepeval_objective/main.py, transformerlab/plugins/deepeval_objective/setup.sh, transformerlab/plugins/eleuther-ai-lm-evaluation-harness-mlx/index.json, transformerlab/plugins/eleuther-ai-lm-evaluation-harness-mlx/main.py, transformerlab/plugins/eleuther-ai-lm-evaluation-harness-mlx/setup.sh, transformerlab/plugins/eleuther-ai-lm-evaluation-harness/index.json, transformerlab/plugins/eleuther-ai-lm-evaluation-harness/main.py, transformerlab/plugins/eleuther-ai-lm-evaluation-harness/setup.sh, transformerlab/plugins/mlx_lora_trainer/main.py, transformerlab/routers/experiment/evals.py
- Adding tensorboard to evals 
- Improved the job data within evals to match training ones closely
- Add a function to add dynamic json fields to job data
=> Tensorboard to evals and improved job data

transformerlab/plugins/common-eleuther-ai-lm-eval-harness-mlx/index.json, transformerlab/plugins/common-eleuther-ai-lm-eval-harness-mlx/main.py, transformerlab/plugins/common-eleuther-ai-lm-eval-harness-mlx/setup.sh, transformerlab/plugins/common-eleuther-ai-lm-eval-harness/index.json, transformerlab/plugins/common-eleuther-ai-lm-eval-harness/main.py, transformerlab/plugins/common-eleuther-ai-lm-eval-harness/setup.sh, transformerlab/plugins/eleuther-ai-lm-evaluation-harness-mlx/index.json, transformerlab/plugins/eleuther-ai-lm-evaluation-harness-mlx/main.py, transformerlab/plugins/eleuther-ai-lm-evaluation-harness-mlx/setup.sh, transformerlab/plugins/eleuther-ai-lm-evaluation-harness/index.json, transformerlab/plugins/eleuther-ai-lm-evaluation-harness/main.py, transformerlab/plugins/eleuther-ai-lm-evaluation-harness/setup.sh, transformerlab/routers/evals.py
- Standardize Eleuther Outputs into a csv
- Route to Compare Evals with each other at "<HOST:PORT>/evals/compare_evals"
=> Standardize Eleuther Output into csv, add route to compare evals

transformerlab/plugins/deepeval_llm_judge/index.json, transformerlab/plugins/deepeval_llm_judge/main.py
Remove `judge_model` and replace with `generation_model` everywhere
=> Fix and make the notation generation_model everywhere

transformerlab/routers/evals.py, transformerlab/routers/experiment/evals.py
- Minor changes for field names
=> Add detailed and summary comparison for evals

transformerlab/plugins/basic_evals/main.py, transformerlab/plugins/common-eleuther-ai-lm-eval-harness-mlx/main.py, transformerlab/plugins/common-eleuther-ai-lm-eval-harness/main.py, transformerlab/plugins/eleuther-ai-lm-evaluation-harness-mlx/main.py, transformerlab/plugins/eleuther-ai-lm-evaluation-harness/main.py, transformerlab/routers/evals.py
- Add individual charts to missing evals plugins
- Fix the pandas deprecation warning
- Current logic shows no chart data whenever a failed job is used to compare
=> Fixes for Evals Comparison

transformerlab/plugins/common-eleuther-ai-lm-eval-harness-mlx/main.py, transformerlab/plugins/common-eleuther-ai-lm-eval-harness/main.py, transformerlab/plugins/eleuther-ai-lm-evaluation-harness-mlx/main.py, transformerlab/plugins/eleuther-ai-lm-evaluation-harness/main.py, transformerlab/routers/experiment/evals.py, transformerlab/routers/experiment/generations.py, transformerlab/shared/shared.py
- Solves bug which prevented evals and generation from running whenever a local model not available on HF was used.
=> Bug fix for crashing local model generation and eval runs

transformerlab/models/filesystemmodel.py, transformerlab/plugins/nanotron_pretrainer/convert_nanotron_to_hf.py, transformerlab/plugins/nanotron_pretrainer/convert_weights.py, transformerlab/plugins/nanotron_pretrainer/index.json, transformerlab/plugins/nanotron_pretrainer/main.py, transformerlab/routers/model.py, transformerlab/shared/shared.py
- Set a train_type within the index.json, if not specified "LoRA" will be used
- Add logic for running a pre-training run 
- Fix bugs and remove redundant parameters for pre-training
- Convert pre-trained model to huggingface format
- Fix import bugs with locally importing models within Transformer Lab due to the new file system
=> Removing Restricted Logic for LoRA Train Type

transformerlab/models/localmodel.py
- Model Provenance
- Model provenance extraction from Job table
- Added a check to see if the job_data column has model_name in it before creating the provenance
=> Model Provenance FIx

test/test_db.py, transformerlab/db.py, transformerlab/shared/models/models.py
We only use it to initialize the config and plugin tables to make sure it works.
=> First attempt at using SQL Alchemy

transformerlab/models/localmodel.py, transformerlab/plugins/embedding_model_trainer/index.json, transformerlab/plugins/embedding_model_trainer/info.md, transformerlab/plugins/embedding_model_trainer/main.py, transformerlab/shared/shared.py
- Embedding Model Plugin
- Created new entry for embedding job_type inside shared.py
- Mapped the entry with index.json
=> Fix/Embedding Models

transformerlab/plugins/fastchat_server/index.json, transformerlab/plugins/fastchat_server/main.py, transformerlab/plugins/fastchat_server/model_worker.py
- Set default as multi-gpu
- Option to set gpu_ids if needed
=> Fastchat Multi GPU

requirements-gpu.in, requirements-no-gpu-uv.txt, requirements-uv.txt, requirements.in
- Fixes protobuf degradation errors caused in some devices
=> Version upgrade for wandb

transformerlab/plugins/mlx_lora_trainer/index.json, transformerlab/plugins/mlx_lora_trainer/main.py, transformerlab/plugins/mlx_lora_trainer/setup.sh
=> Fix wandb import issues due to protobuf upgrades from mlx-lm

transformerlab/plugins/synthesizer_docs/index.json, transformerlab/plugins/synthesizer_docs/info.md
Updated Documentation for Max Context > 100
=> Added changes to synthesizer docs plugin documentation

api.py, transformerlab/routers/model.py
- Add secure_filename for deleting adaptors
=> Fix deleting adaptors

transformerlab/plugins/mlx_server/main.py
- Fixes displaying logprobs properly in tooltip
=> Fix the top logprobs in MLX Server

transformerlab/plugins/fastchat_server/index.json, transformerlab/plugins/fastchat_server/model_worker.py
Note: Logprobs won't work right now as TextIterator would not give direct access to model logits but I'll figure out a different way to access those in a follow-up PR
=> Enable Gemma 3 Base and Instruct for chat and completions

transformerlab/plugins/fastchat_server/model_worker.py
- This adds model support for Gemma 3 models
- Also solves the issue of occasional failures when using Qwen models
=> Make the Model Activations compatible with bfloat16 models

transformerlab/models/localmodel.py, transformerlab/plugin_sdk/transformerlab/sdk/v1/train.py, transformerlab/plugins/embedding_model_trainer/index.json, transformerlab/plugins/embedding_model_trainer/info.md, transformerlab/plugins/embedding_model_trainer/main.py, transformerlab/shared/shared.py
Fixes:
- Fixes tasks queue to remove the second config inside the input['config']
- Fixes Model Provenance to support json coming out of the new db
- Fixes a minor bug which caused issues with saving in embedding-model-trainer
- Fixes a major bug in Embedding Model Trainer which is caused on single GPU machines if using Matryoshka loss and single sentences dataset type
=> Fix training bugs and some other minor bugs

transformerlab/routers/serverinfo.py
Fix the disk usage on Mac OS by using the diskutil to get the disk usage
=> Fixes Issue #333 on app

transformerlab/models/localmodel.py, transformerlab/shared/batched_requests.py
- Add 0.01s delay to batched requests
- Make the is_sentence_transformer module to look within local_files_only
=> Fixes for Batching and Is_sentence_transformer

transformerlab/fastchat_openai_api.py, transformerlab/plugins/fastchat_server/index.json, transformerlab/plugins/fastchat_server/model_worker.py, transformerlab/plugins/mlx_server/index.json, transformerlab/plugins/mlx_server/main.py
...and change activation endpoint names for Fastchat and MLX
=> Add model architecture visualization in Fastchat and MLX

api.py, requirements-no-gpu-uv.txt, requirements-uv.txt, requirements.in, transformerlab/plugins/llama_trainer/index.json, transformerlab/plugins/llama_trainer/main.py, transformerlab/routers/job_sdk.py
- Handles llama trainer GPU Device Assignment before trl is imported now
=> Upgrade transformers version to v4.51

api.py, scripts/xml-rpc-client-example/example-with-retries.py, scripts/xml-rpc-client-example/tlab_sdk_client/callbacks/hf_callback.py, scripts/xml-rpc-client-example/tlab_sdk_client/client.py, scripts/xml-rpc-client-example/train_example.py, scripts/xml-rpc-client-example/training_client_example.py, transformerlab/db.py, transformerlab/models/localmodel.py, transformerlab/plugin_sdk/transformerlab/plugin.py, transformerlab/plugin_sdk/transformerlab/sdk/v1/tlab_plugin.py, transformerlab/plugin_sdk/transformerlab/sdk/v1/train.py, transformerlab/routers/job_sdk.py, transformerlab/routers/train.py
Additional things:
- Add model provenance for local models
- Add ability to create provenance files for local models not limited to "Transformerlab/"
=> Job SDK for tlab client

scripts/xml-rpc-client-example/tlab_sdk_client/client.py, transformerlab/db.py, transformerlab/plugins/t5_lora_trainer/index.json, transformerlab/plugins/t5_lora_trainer/main.py
- Adding 5 second wait time for Writer and putting the sync connection in WAL mode
- Consolidating all sync connections to make use of one object only.
- Changed the T5 LoRA trainer to use plugin sdk to remove bare db access
=> Fix db locks issue when executing remotely

transformerlab/plugins/autotrain_sft_trainer/index.json, transformerlab/plugins/autotrain_sft_trainer/main.py, transformerlab/plugins/autotrain_sft_trainer/setup.sh, transformerlab/plugins/dpo_orpo_simpo_trainer_llama_factory/index.json, transformerlab/plugins/dpo_orpo_simpo_trainer_llama_factory/main.py, transformerlab/plugins/reward_modeling_llama_factory/index.json, transformerlab/plugins/reward_modeling_llama_factory/main.py, transformerlab/plugins/sft_llama_factory/index.json, transformerlab/plugins/sft_llama_factory/main.py
- Fixes errors in older trainer plugins
- Reviving them to work again
=> Revive all older trainer plugins with tlab_trainer

requirements-no-gpu-uv.txt, requirements-uv.txt, requirements.in
Solves transformerlab/transformerlab-app#379
=> Add support for models stored using XET storage on HF Hub

transformerlab/fastchat_openai_api.py
Fixes transformerlab/transformerlab-app#377
=> Upgrade Pydantic things from .dict() to .model_dump()

transformerlab/plugins/mlx_lora_trainer/index.json, transformerlab/plugins/mlx_lora_trainer/main.py
- Setting epochs overrides the number of iterations set
- Fixes transformerlab/transformerlab-app#39
=> Add epoch based training for MLX LoRA Trainer

requirements-no-gpu-uv.txt, requirements.in, transformerlab/routers/serverinfo.py
Fixes transformerlab/transformerlab-app#387
=> Add Macmon specific metrics

transformerlab/plugins/fastchat_server/index.json, transformerlab/plugins/mlx_server/index.json
- Adds supports for fastchat_server and mlx_server
- Fixes transformerlab/transformerlab-app#398
=> Add filtering based on the supports field for interact in loader plugins

transformerlab/fastchat_openai_api.py
Fixes transformerlab/transformerlab-app#36
=> Fix Token Count in Interact tab

transformerlab/routers/plugins.py
Fixes transformerlab/transformerlab-app#388
=> Auto update plugins on startup

transformerlab/routers/experiment/export.py
Fixes transformerlab/transformerlab-app#40
=> Fix names for output of exporter models

transformerlab/galleries/model-gallery.json, transformerlab/plugins/fastchat_server/index.json
and update the fastchat server to support
Qwen3's two model architectures.
=> Add Qwen3 to the model gallery

transformerlab/routers/experiment/plugins.py, transformerlab/routers/plugins.py
Fixes transformerlab/transformerlab-app#420
=> Plugin install API returns an error message on failure.

install.sh, requirements-no-gpu-uv.txt, transformerlab/plugins/llama_cpp_server/index.json, transformerlab/plugins/llama_cpp_server/setup.sh, transformerlab/routers/plugins.py
Fixes transformerlab/transformerlab-app#432
=> Separate builds for MacOS and CPU-only devices

requirements-no-gpu-uv.txt, requirements-uv.txt, transformerlab/plugins/mlx_server/index.json, transformerlab/plugins/mlx_server/main.py
Fixes transformerlab/transformerlab-app/issues/436
=> Set manual context length for fallback on MLX Server

.github/workflows/pytest-server-test.yml, .github/workflows/pytest.yml, test/server/conftest.py, test/server/test_config.py, test/server/test_server_info.py
Added back tests for install and live server run. We are currently testing the server_info things to make sure API routes work and there is a test for config which verifies if DB is setup properly or not
=> Add back tests for install and server run

test/db/test_db.py, transformerlab/db.py
This adds tests to the workflow db endpoints in db.py
=> test workflow db

test/api/test_model.py, transformerlab/galleries/model-group-gallery.json, transformerlab/routers/model.py, transformerlab/shared/galleries.py
the model.py and galleries.py now sync model-group-gallery.json with the version inside galleries upon startup
=> Added the ability to pull model group gallery from galleries on startup

.github/workflows/pytest.yml, test/README.md, test/installer/test_install_dot_sh.py
This change adds a new test via Pytest that runs shellcheck on install.sh to make sure there are no bash scripting errors
=> Test the install.sh with shellcheck

requirements-no-gpu-uv.txt, requirements-rocm-uv.txt, requirements-uv.txt, transformerlab/fastchat_openai_api.py, transformerlab/plugins/fastchat_server/index.json, transformerlab/plugins/fastchat_server/model_worker.py, transformerlab/plugins/fastchat_server/setup.sh, transformerlab/plugins/mlx_server/index.json, transformerlab/plugins/mlx_server/main.py, transformerlab/routers/batched_prompts.py
- Depends on transformerlab/transformerlab-inference#6
- To be merged only after pypi release of tlab-inference
=> Add Min P Sampling during Inference

test/api/test_workflows.py, transformerlab/routers/experiment/workflows.py
Response to https://github.com/transformerlab/transformerlab-app/issues/551
=> Cancel Workflow API endpoint

requirements.in
=> One liner: transformerlab-inference in requirements twice

transformerlab/plugins/llamaindex_simple_document_search/index.json, transformerlab/plugins/llamaindex_simple_document_search/main.py
This fix prevents anything from writing to stdout becuase output from this script needs to be clean JSON
=> Force Llama Index to Print to STDERR

test/api/test_server_info.py, transformerlab/routers/serverinfo.py
- This stops sending info about flash attention in Computer Tab since we don't install it
=> Suppress information about flash_attn

transformerlab/plugins/llama_trainer/index.json, transformerlab/plugins/llama_trainer/main.py
- Fixes HIP memory issues on AMD GPUs
=> Fix Huggingface TRL Trainer on the AMD Machine

transformerlab/routers/experiment/experiment.py, transformerlab/routers/experiment/workflows.py, transformerlab/routers/recipes.py
- Fix workflow creation from recipes
- Fix experiment names and add secure_filename
=> Fix Recipes (workflows and exp creation)

transformerlab/fastchat_openai_api.py, transformerlab/plugin_sdk/transformerlab/sdk/v1/tlab_plugin.py
Also fixes pydantic deprecation warnings
=> Make SDK stop the worker if the SDK started it

test/plugin_sdk/test_plugin.py, transformerlab/plugin_sdk/transformerlab/plugin.py, transformerlab/plugins/fastchat_server/main.py, transformerlab/plugins/sglang_server/main.py, transformerlab/plugins/vllm_server/main.py
for issue https://github.com/transformerlab/transformerlab-app/issues/619
=> centralize worker PID file writing

transformerlab/routers/data.py
Fixes: #617
https://github.com/transformerlab/transformerlab-app/issues/617
=> Improve error message for invalid or private Hugging Face dataset IDs

transformerlab/plugins/mlx_exporter/index.json, transformerlab/plugins/mlx_exporter/setup.sh, transformerlab/plugins/mlx_lora_trainer/index.json, transformerlab/plugins/mlx_lora_trainer/setup.sh, transformerlab/plugins/mlx_rlaif_trainer/index.json, transformerlab/plugins/mlx_rlaif_trainer/setup.sh, transformerlab/plugins/mlx_server/index.json, transformerlab/plugins/mlx_server/setup.sh, transformerlab/plugins/mlx_vlm_server/index.json, transformerlab/plugins/mlx_vlm_server/setup.sh, transformerlab/routers/serverinfo.py
=> Update MLX to 0.26.1

requirements-no-gpu-uv.txt, requirements-rocm-uv.txt, requirements-rocm.in, requirements-uv.txt, requirements.in, transformerlab/routers/data.py
Sample dataset to try: `raghib-blockstak/sample_audio_3`
=> Add audio datasets support

transformerlab/plugins/yourbench_data_gen/index.json, transformerlab/plugins/yourbench_data_gen/main.py, transformerlab/plugins/yourbench_data_gen/setup.sh, transformerlab/routers/plugins.py
This adds a special condition to create the plugin venv at python 3.12 for yourbench.
Fixes transformerlab/transformerlab-app#750
=> Fix python environment and internal errors of yourbench plugin

api.py, requirements-no-gpu-uv.txt, requirements-rocm-uv.txt, requirements-rocm.in, requirements-uv.txt, requirements.in, test/api/test_plugins.py, transformerlab/db/filesystem_migrations.py, transformerlab/fastchat_openai_api.py, transformerlab/models/localmodel.py, transformerlab/models/ollamamodel.py, transformerlab/routers/batched_prompts.py, transformerlab/routers/data.py, transformerlab/routers/experiment/diffusion.py, transformerlab/routers/experiment/evals.py, transformerlab/routers/experiment/export.py, transformerlab/routers/experiment/generations.py, transformerlab/routers/experiment/plugins.py, transformerlab/routers/experiment/rag.py, transformerlab/routers/experiment/workflows.py, transformerlab/routers/model.py, transformerlab/routers/plugins.py, transformerlab/routers/prompts.py, transformerlab/routers/serverinfo.py, transformerlab/shared/dirs.py, transformerlab/shared/galleries.py, transformerlab/shared/shared.py, transformerlab/shared/ssl_utils.py
Depends on transformerlab/transformerlab-sdk#22
Tests will fail before merging the sdk PR
=> Change all dirs to functions
